# Generated by Django 4.2.5 on 2024-01-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
